// app/layout.js
import localFont from "next/font/local";
import Navigation from "../app/components/Navigations/Header";
import Sidebar from "./components/SideBar/Sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Добавляем общие элементы лейаута */}
        <Navigation />

        <div className="flex">
          {/* Sidebar присутствует на всех страницах */}
          <Sidebar />
          
          {/* Основной контент страницы */}
          <div className="flex-grow">
            {children}
          </div>
        </div>

        <footer>
          {/* Футер также на всех страницах */}
        </footer>
      </body>
    </html>
  );
}
